version: "3.8"

services:
  addon_service:
    build: .
    restart: unless-stopped
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: app.settings
      PYTHONUNBUFFERED: 1
    ports:
      - 8000:8000
    stdin_open: true
    volumes:
      - ./:/code:cached
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - "${POSTGRES_DATA_VOL:-postgres_data_vol}:/var/lib/postgresql/data/"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres_data_vol:
    external: false
