name: Addon Service Base

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements/dev-requirements.txt
    - name: Run Syntax
      run: pre-commit run --all-files --show-diff-on-failure
    - name: Run Tests
      run: python3 manage.py test
